### ISSUE TITLE
Planejamento

### ISSUE THREAD

**Issue by wallacesilva** [virtore/docs#1]
## Problema

Planejar o que será e o que precisa ser feito em cada fase para que todos podem ter ciencia em que passo se está e até poderem ajudar.

## Proposta

Essa é uma ideia ainda, mas pensando em como deixar organizando as milestones para conseguir ir arrumando o projeto aos poucos.

ToDo:

- [ ] Criar issues de documentação de páginas (pode ser uma com ToDos);
  - [ ] Página de sobre o projeto, quem sou eu, e outros;
  - [ ] Página de como ajudar;
  - [ ] Página de integrações;
  - [ ] Página de ideias futuras;
  - [ ] Página de versionamentos;
  - [ ] Página de Estrutura de URL e onde encontrar as coisas (sitemap?);
  - [ ] Página de Proposta de Templates;
- [ ] Criar issue para Criar o Swagger (Open Api 3) da estrutura de dados inicial;
- [ ] Criar issue para Definir Stack inicial do Virtore Server (API);

**Milestone 1**
- Criar e configurar site, blog e redes sociais
- Iniciar projeto *Virtore Server (API)*
- Divulgar projeto (blogs, rede sociais)
- Analisar e Definir:
  - Estrutura de dados básica do sistema
  - Banco de dados a ser usado
  - Versionamento
  - Terá padrão de LTS (long time support)
  - Padrão de comunicação na API (c/ JWT)
  - Processo de Migração monolítico para distribuído (com mensagem?)
- Criar documentação do projeto inicial

**Milestone 2**
- Criar sdk python básica consumindo a api do server
- Criar sdk php básica consumindo a api do server
- Definir se vale a pena um sistema de template cross language
- Escrever artigos sobre o processo de desenvolvimento
- Escrever artigo sobre o que já aprendemos

**Milestone 3**

- Criar integração inicial com Correios e outros de entrega
- Criar integração inicial com Gateways de Pagamento
- Iniciar web python consumindo o api server usando a sdk
- Escrever artigos sobre o processo de desenvolvimento

**Milestone X (indefinido)**

- Ferramentas de migração para Virtore (from magento, open cart, oscommerce)
- Criar módulos adicionais de integração (ex Pagar.Me, Bling)

---

Outras ideias e propostas de planejamento veja o Google Docs que criei e fui arrumando as ideias lá: https://docs.google.com/document/d/19Gj9okACJtMYssjKl7g1jn0yaenoy8rYyDGMB4oLIv8/edit?usp=sharing
